plugins {
    id 'application'
    id 'java'
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass = 'com.example.booktracker.Main'
}

dependencies {
    implementation 'org.xerial:sqlite-jdbc:3.40.1.0'
}
